mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path





urlpatterns = [

    
   
      
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
   
   
]

mysite/polls/urls.py
from django.urls import path
from django.contrib.auth import views 
from . import views




app_name = 'polls'
urlpatterns = [
    
   
    path('', views.Home.as_view(), name = 'home'),
    path("accounts/login/", views.LoginView.as_view(), name='register'),
    path("accounts/logout/", views.logout_view, name='log-out'),
    path('main/', views.MainView.as_view(), name='main'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
   
]

mysite/polls/models.py
import datetime

from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now
    
    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True, 
        ordering='pub_date', 
        description='Published recently?', 

    )
    def was_pulished_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    
    def __str__(self):
        return self.choice_text
    
class CreateQues(models.Model):
   question = models.ForeignKey(Question, on_delete=models.CASCADE, default='1')
   choice = models.ForeignKey(Choice, on_delete=models.CASCADE, default='1')
   completed = models.BooleanField(default=False)
   created_at = models.DateTimeField(auto_now_add=True)


#https://swapps.com/es/blog/trabajando-con-formularios-anidados-con-django/


#>>> from polls.models import Choice, Question  # Import the model classes we just wrote.
#
## No questions are in the system yet.
#>>> Question.objects.all()
#<QuerySet []>
#
## Create a new Question.
## Support for time zones is enabled in the default settings file, so
## Django expects a datetime with tzinfo for pub_date. Use timezone.now()
## instead of datetime.datetime.now() and it will do the right thing.
#>>> from django.utils import timezone
#>>> q = Question(question_text="What's new?", pub_date=timezone.now())
#
## Save the object into the database. You have to call save() explicitly.
#>>> q.save()
#
## Now it has an ID.
#>>> q.id
#1
#
## Access model field values via Python attributes.
#>>> q.question_text
#"What's new?"
#>>> q.pub_date
#datetime.datetime(2012, 2, 26, 13, 0, 0, 775217, tzinfo=datetime.timezone.utc)
#
## Change values by changing the attributes, then calling save().
#>>> q.question_text = "What's up?"
#>>> q.save()
#
## objects.all() displays all the questions in the database.
#>>> Question.objects.all()
#<QuerySet [<Question: Question object (1)>]>
#

mysite/polls/forms.py
from django import forms    
from .models import CreateQues, Choice, Question




class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class ChoiceInline(forms.Form):
    model = Choice
    extra = 3


class CreateQuestionForm(forms.ModelForm):

    class Meta:
        model = CreateQues
        fields = ('question_text',
                   'pub_date', 'choice_text', 
                   'votes',
                   'completed', )

        widgets = {
            'question_text': forms.TextInput(attrs={'class': 'form-control',}),
            'pub_date':forms.DateTimeInput( attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'}),
            
            
            'completed': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            
        }

        #inlines = [ChoiceInline]
        #list_display = ('question_text', 'pub_date', 'was_published_recently')
        #list_filter = ['pub_date']
        #search_fields = ['question_text']

##django.core.exceptions.FieldError: Unknown field(s) (pub_date, votes, question_text, choice_text) specified for CreateQues

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404, redirect 

from django.contrib.auth import authenticate, login, logout
from django.urls import reverse, reverse_lazy

from .models import Question, Choice, CreateQues
from .forms import LoginForm, CreateQuestionForm

from django.contrib.auth import views as auth_views
from django.contrib import messages
from django.views import generic
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils import timezone
from django.http import HttpResponseRedirect



class Home(TemplateView):
    template_name = 'polls/home.html'


class MainView(generic.list.ListView):
    model = Question
    template_name = 'polls/index.html'
    
      
    def get_context_data(self, **kwargs):
        self.object_list = self.get_queryset()
        context = super(MainView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
      #  print(context)
        return context
    
    def get_object(self):
        return Question.objects.all().order_by('-pub_date')

    
    def get(self, request):
        if  not request.user.is_authenticated:
        # messwages.warning(request, 'MENSAJE: Usuario no logeado')
            return redirect(reverse('polls:register'))
        else:
            
            #import pdb; pdb.set_trace()
            context = self.get_context_data()
            return render(request, self.template_name, context)

class DetailView(generic.DetailView):
    #import pdb; pdb.set_trace()   
    model = Question
    template_name = 'polls/detail.html'


    def get_queryset(self):
        
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte = timezone.now())      
   
def vote(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
        else:
            selected_choice.votes += 1
            selected_choice.save()
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class ResultView(generic.DetailView):
    model =   Question
    template_name = 'polls/results.html'


##  LOGIN VEW   #######

class LoginView(auth_views.LoginView):
    template_name = 'registration/login.html'
    form = LoginForm()

         
    def get(self, request):
        #import pdb; pdb.set_trace()
        if request.method == 'GET':
            form = LoginForm()
            return render(request, self.template_name, {'form': form}) 
        else:
            messages.warning(request, 'no existe formilario') 

        if request.user.is_authenticated:
            return redirect(reverse('polls:main'))
        else: 
            return render(request, self.template_name)   

    def post(self, request):
        form = LoginForm()
        #import pdb; pdb.set_trace()
        username = request.POST['username']
        password = request.POST['password']

        #import pdb; pdb.set_trace()
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('polls:main')  #  redirigir al usuario después de iniciar sesión.
        else:
            # Handle authentication failure (e.g., show an error message)
            messages.error(request, 'La contraseña o el usuario son incorrectos, verifica los datos')
            form = LoginForm()
            return render(request, self.template_name, {'form': form}) 

def logout_view(request):
    logout(request)#toma el request de la pagina con el url asignado y retornar la peticion
    messages.warning(request, 'MENSAJE: El usuario ha cerrado la sesion')
    #redirigiendo al home
    return redirect(reverse('polls:home'))

##      CRUD VIEWS          #####


class TaskListView(ListView):
    model = CreateQues
    template_name = 'ques_list.html'
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = CreateQues
    template_name = 'crud/ques_detail.html'


class TaskCreateView(CreateView):
    model = CreateQues
    form_class = CreateQuestionForm
    template_name = 'crud/ques_form.html'
    success_url = reverse_lazy('ques_list')


class TaskUpdateView(UpdateView):
    model = CreateQues
    form_class = CreateQuestionForm
    template_name = 'crud/task_form.html'
    success_url = reverse_lazy('ques_list')

class TaskDeleteView(DeleteView):
    model = CreateQues
    template_name = 'task_manager/task_confirm_delete.html'
    success_url = reverse_lazy('task_list')

mysite/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/detail.css' %}">

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="vote">
    
    </form>
  
    </div>
    <br><a class="btn" href="{% url 'polls:main' %}">Volver a las encuestas</a>

mysite/polls/templates/polls/home.html
{% extends "base.html" %}

{% load static %}




{% if next %}
    {% if user.is_authenticated %}
   
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}



 {% block content %}
        <link rel="stylesheet" href="{% static 'polls/home.css' %}">
  
        
        

        <h1>Hola esta es otra prueba</h1>

        <div class="tarjeta">
            <div class="titulo">Bien venido,  ¿quieres ingresar a las encuestas?</div>
            <div class="cuerpo">
               
            </div>
            
                <a  class="pie" href="{% url 'polls:main' %}">Vamos a ello</a>
           
            </div>
        </div>
 {% endblock content %}

mysite/polls/templates/polls/index.html
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'style.css' %}">

    {% if user.is_authenticated %}
    <h3>  Hi {{ user.username }}! </h3>
    <p><a href="{% url 'polls:log-out' %}">Log Out</a></p> 
    {% else %}
   {#No mostrará nada#}
    {% endif %}

    {% if object_list %}
    <ul>
    {% for question in object_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    
    {% endfor %}
    </ul>

    {% else %}
    <p>No polls are available.</p>
    {% endif %}

{% endblock content %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

            
<br><a  class="pie" href="{% url 'polls:main' %}">Volver a las encuestas</a>